title: "MCPU Slideshow"
baseurl: "/project"
url: "https://cleanper.github.io/MCPU-Page/"

markdown: kramdown
permalink: pretty

incremental: true

jekyll_minifier:
  uglifier:
    harmony: true
    compress:
      sequences: true
      dead_code: true
      conditionals: true
      booleans: true
      unused: true
      if_return: true
      join_vars: true
      drop_console: true
  css_sass:
    style: :compressed
  html:
    remove_comments: true
    remove_intertag_spaces: true
    remove_quotes: true
    simple_doctype: true
    preserve_line_breaks: false

exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - README.md

include:
  - "*.flac"
  - "*.mp3"
  - "*.png"
  - "*.js"
  - "*.css"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
